// backend_tools/parse_fixtures.js
const fs = require('fs');
const path = require('path');

const sourceDir = path.join(__dirname, 'results_source');
const rootDataPath = path.join(__dirname, '../data.js');

// Regex to catch rows
const rowRegex = /^(\d+)\s+(\d+)\s+(.+?)\s+(\d+)\s+([MF])\s+(Senior|V\d+\+?)\s+(.+?)\s+(\d{2}:\d{2}:\d{2})\s+(\d+)\s+(\d+)\r?$/;

let allCompiledResults = [];

if (!fs.existsSync(sourceDir)) {
    console.error(`Error: Source directory ${sourceDir} does not exist.`);
    process.exit(1);
}

// Read all source text files
const files = fs.readdirSync(sourceDir);

// ... upper regex code stays the same ...

files.forEach(filename => {
    if (!filename.endsWith('.txt')) return;

    const parts = filename.replace('.txt', '').split('_');
    if (parts.length < 4) return;

    const discipline = parts[0];
    const season = `${parts[1]}/${parts[2]}`;
    const race_number = parseInt(parts[3], 10);

    const filePath = path.join(sourceDir, filename);
    const fileContent = fs.readFileSync(filePath, 'utf8');
    const lines = fileContent.split('\n');

    let venue = "Unknown Venue";
    let date = "";
    let distance = "";
    let status = "Confirmed"; // Default status

    const parsedResults = [];

    lines.forEach((line) => {
        const cleanLine = line.trim();
        if (!cleanLine) return;

        if (cleanLine.startsWith('#')) {
            if (cleanLine.toUpperCase().startsWith('# VENUE:')) venue = cleanLine.split(':')[1].trim();
            if (cleanLine.toUpperCase().startsWith('# DATE:')) date = cleanLine.split(':')[1].trim();
            if (cleanLine.toUpperCase().startsWith('# DISTANCE:')) distance = cleanLine.split(':')[1].trim();
            if (cleanLine.toUpperCase().startsWith('# STATUS:')) status = cleanLine.split(':')[1].trim();
            return;
        }

        const match = cleanLine.match(rowRegex);
        if (match) {
            parsedResults.push({
                pos: parseInt(match[1], 10),
                bib: match[2],
                name: match[3].trim(),
                age: parseInt(match[4], 10),
                sex: match[5],
                age_cat: match[6],
                club: match[7].trim(),
                time: match[8],
                gender_pos: parseInt(match[9], 10),
                cat_pos: parseInt(match[10], 10),
                race_number,
                discipline,
                season,
                venue,
                date,
                distance,
                status
            });
        }
    });

    // If the race was cancelled and has no finisher rows, push a placeholder record 
    // so the frontend engine still knows this fixture exists in the calendar sequence.
    if (status.toLowerCase() === 'cancelled' && parsedResults.length === 0) {
        parsedResults.push({
            race_number,
            discipline,
            season,
            venue,
            date,
            distance,
            status: "Cancelled",
            pos: 0, club: "", name: "", sex: "", age_cat: "", cat_pos: 0, gender_pos: 0 // placeholders
        });
    }

    console.log(`Parsed ${filename}: ${status === 'Cancelled' ? 'CANCELLED' : 'Found ' + parsedResults.length + ' finishers'} at ${venue}`);
    allCompiledResults = allCompiledResults.concat(parsedResults);
});

// ... lower sorting and write code stays the same ...

// Sort the compiled results globally by season, discipline, race number, then position
allCompiledResults.sort((a, b) => {
    if (a.season !== b.season) return b.season.localeCompare(a.season);
    if (a.discipline !== b.discipline) return a.discipline.localeCompare(b.discipline);
    if (a.race_number !== b.race_number) return a.race_number - b.race_number;
    return a.pos - b.pos;
});

// Write directly out to root data.js
const jsContent = `// This file is auto-generated by backend_tools/parse_fixtures.js. Do not edit manually.\nwindow.glclResults = ${JSON.stringify(allCompiledResults, null, 4)};\n`;
fs.writeFileSync(rootDataPath, jsContent, 'utf8');

console.log(`\nAutomated Build Success: Compiled ${allCompiledResults.length} total rows into root 'data.js'.`);